
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

opacity = 1.0
blur = false

startup_mode = "Fullscreen"

# option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[general]
import = [
  "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
